ln -sv ~/dotfiles/.bash_profile ~
ln -sv ~/dotfiles/.bash_aliases ~
ln -sv ~/dotfiles/.bashrc ~
ln -sv ~/dotfiles/.i3/ ~
ln -sv ~/dotfiles/..oh-my-zsh ~
ln -sv ~/dotfiles/.oh-my-zsh ~
ln -sv ~/dotfiles/.p10k.zsh ~
ln -sv ~/dotfiles/.tmux.comf ~
ln -sv ~/dotfiles/.vimrc ~
ln -sv ~/dotfiles/.zshrc ~
ln -sv ~/dotfiles/.config/nvim/init.vim ~/.config/nvim/init.vim
